version: '3.9'
services:
    app:
        build: .
        environment:
            - PHX_HOST=localhost
            - DATABASE_URL=ecto://root:password@database:5432/liveprompt_dev
            - SECRET_KEY_BASE="gOJB97i23ufdq49KAfRSDq39Pu7okaU2ZTrzrj1PRs1+N4YRY0Y2QDJg83v0JbhV"
            - PORT=8080
        ports:
            - 8081:8080
        command: tail -f /dev/null

    database:
        image: 'ankane/pgvector'
        volumes:
            - ./db-data:/var/lib/postgresql/data/
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: liveprompt_dev
        ports:
            - 5432:5432
