version: '3.9'
services:
    app:
        build: .
        environment:
            - APP_ENV=$APP_ENV
            - PHX_SERVER=true
            - PHX_HOST=$HOST
            - DATABASE_URL=ecto://root:password@database:5432/liveprompt_dev
            - SECRET_KEY_BASE="$SECRET_KEY_BASE"
            - SENDGRID_API_KEY="$SENDGRID_API_KEY"
            - PORT=8080
        ports:
            - 8080:8080
        command: tail -f /dev/null
