version: '3.9'
services:
    app:
        build: .
        environment:
            - PHX_HOST=localhost
            - DATABASE_URL=ecto://root:password@host.docker.internal:5432/liveprompt_dev
            - SECRET_KEY_BASE="$SECRET_KEY_BASE"
            - SENDGRID_API_KEY="$SENDGRID_API_KEY"
            - PORT=8080
        ports:
            - 8080:8080
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        command: tail -f /dev/null
